```{r, echo=FALSE, strip.white=FALSE}
REPLACE <- "REPLACE"
```

## Methods

### Outcome

Sykdomspulsen skal være et system for anonym sanntidsovervåking av sykdommer eller symptomer basert på diagnoser satt ved konsultasjoner i allmennpraksis. Sykdomspulsen skal daglig få inn anonyme data om legekonsultasjoner med sykdoms- eller symptomdiagnose fra landets legekontorer. Data skal samles inn via Helsedirektoratet (KUHR-systemet ) som får tilsendt informasjon i forbindelse med legenes refusjonskrav. The ICPC2 codes used for gastroenteritis are: D11 (Diarrhea), D70 (Tarminfeksjon), D73 (Gastroenteritt antatt infeksiøs).

The Sykdomspulsen algorithm is a quasi-Poisson regression counting the number of cases from a population offset of number of consultations. The regression model is adjusted for trend and seasonality (using sine/cosine weekly transformations). Previous outbreaks are downweighted using the Farrington method. Outbreaks are determined to be any value where the observed value is higher than two standard deviations from the predicted.

We applied the algorithm twice: once using only physical doctor consultations, and again using both physical doctor consultations and telephone consultations.

After applying the Sykdomspulsen algorithm to each municipality at the weekly level, we had a dichotomous outbreak/not-outbreak outcome for each municipality for each week.

### Exposures

Three variables were of interest to us: runoff (municipal average using gridded data), temperature corrected precipitation (municipal average using gridded data), and rain (weather station located nearest to municipal centre).

For each of these variables, we transformed their daily values into "extreme" vs "not-extreme". We created two daily dichotomous variables using two different cutoffs: the 95th and 99th percentiles (municipal specific). We then summed these variables over iso-weeks, generating variables representing "the number of extreme days in week X".

For each of these exposure variables, we were interested in lags of 0, 1, 2, 3, and 4 weeks. We subsequently analysed these exposure variables both continuously and categorising them into 0, 1-3 extreme days, and 4+ extreme days.

### Stratified analyses

We performed analyses in five strata: all data, Aatumn (September, October, November), winter (December, January, February), spring (March, April, May), and summer (June, July, August).

### Model

A mixed effects binomial regression model was applied, with random intercepts for each municipality. This model was run for each combination of outcome (doctors only vs doctors+telephone), exposure variable (runoff, temperature corrected precipitation, and rain), exposure cutoff (95 and 99th percentiles), exposure transformation (continuous vs categorical), and time period (all year, autumn, winter, spring, and summer).

## Results

- Didn't appear to be anything really significant in the 99th percentiles, probably due to low power
- More rain, corrected precipitation, runoff, 2-4 weeks lagged, seemed to have a protective effect against visiting doctors
- More rain, corrected precipitation, runoff, 2-4 weeks lagged, seemed to have a less-robust protective effect against visiting doctors+telephone
