---
title: "Mouse Radiation"
author: Richard White
date: "`r lubridate::today()`"
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

# Neccessary functions
```{r, results='hide', message=FALSE, warning=FALSE}
RAWmisc::AllowFileManipulationFromInitialiseProject()
RAWmisc::InitialiseProject(
  HOME = "/git/code_major/2017/lamprini_momir_sample_size/",
  RAW = "/analyses/data_raw/code_major/2017/lamprini_momir_sample_size/",
  CLEAN = "/analyses/data_clean/code_major/2017/lamprini_momir_sample_size",
  BAKED = "/analyses/results_baked/code_major/2017/lamprini_momir_sample_size/",
  FINAL = "/analyses/results_final/code_major/2017/lamprini_momir_sample_size/",
  SHARED = "/dropbox/results_shared/code_major/2017/lamprini_momir_sample_size/")

suppressWarnings(suppressMessages(library(data.table)))
suppressWarnings(suppressMessages(library(ggplot2)))

GenerateSample <- function(N=10000,OR=2){
  age <- rep(0:3,N/4)
  isMale <- rep(0:1,N/2)
  salmonella <- rep(0:3,N/4)
  isAntibiotics <- rep(0:1,N/2)
  
  xData <- data.table(
    age=sample(age),
    isMale=sample(isMale),
    salmonella=sample(salmonella),
    isAntibiotics=sample(isAntibiotics))
  
  xData[,z:=-2.5]
  xData[age!=0,z:=z+log(OR)]
  xData[isMale!=0,z:=z+log(OR)]
  xData[salmonella!=0,z:=z+log(OR)]
  xData[isAntibiotics!=0,z:=z+log(OR)]
  xData[,pr:=1/(1+exp(-z))]
  xData[,y:=rbinom(.N,1,pr)]
  
  return(xData)
}

PValues <- function(N=10000,OR=2){
  xData <- GenerateSample(N=N,OR=OR)
  
  fit0 <- glm(y~factor(age)+isMale+factor(salmonella)+isAntibiotics,data=xData, family="binomial")
  
  fit1 <- glm(y~isMale+factor(salmonella)+isAntibiotics,data=xData, family="binomial")
  pAge <- lmtest::lrtest(fit0,fit1)$`Pr(>Chisq)`[2]
  
  fit1 <- glm(y~factor(age)+factor(salmonella)+isAntibiotics,data=xData, family="binomial")
  pMale <- lmtest::lrtest(fit0,fit1)$`Pr(>Chisq)`[2]
  
  fit1 <- glm(y~factor(age)+isMale+isAntibiotics,data=xData, family="binomial")
  pSalmonella <- lmtest::lrtest(fit0,fit1)$`Pr(>Chisq)`[2]
  
  fit1 <- glm(y~factor(age)+isMale+factor(salmonella),data=xData, family="binomial")
  pAntibiotics <- lmtest::lrtest(fit0,fit1)$`Pr(>Chisq)`[2]
  
  pval <- data.table(
    var=c("age","male","salmonella","antibiotics"),
    p=c(pAge,pMale,pSalmonella,pAntibiotics),
    N=N,
    OR=OR
  )
  
  return(pval)
}

```

\newpage

# Observing the data with N=10,000
```{r}
d <- GenerateSample(N=10000,OR=3)
fit0 <- glm(y~factor(age)+isMale+factor(salmonella)+isAntibiotics,data=d, family="binomial")
summary(fit0)

mean(d$y)

xtabs(~d$age)
xtabs(~d$y + d$age)

xtabs(~d$isMale)
xtabs(~d$y + d$isMale)

xtabs(~d$salmonella)
xtabs(~d$y + d$salmonella)

xtabs(~d$isAntibiotics)
xtabs(~d$y + d$isAntibiotics)

```

# Power calculations
```{r}
set.seed(4)
retval <- vector("list", 3000)
index <- 1
for(N in c(100,152,200,300,400,500,600,700,800,900,1000)){
  print(N)
  for(OR in c(2,3,4)) for(i in 1:1000){
    retval[[index]] <- PValues(N=N,OR=OR)
    index <- index + 1
  }
}
retval <- rbindlist(retval)

retval[,isSig:=0]
retval[p<0.05,isSig:=1]

retval[,isBonfSig:=0]
retval[p<0.05/4,isBonfSig:=1]

power <- retval[,.(power=mean(isSig),
                  powerBonf=mean(isBonfSig)),by=.(N,OR,var)]
print(power)
openxlsx::write.xlsx(power,file=file.path(RAWmisc::PROJ$SHARED_TODAY,"power.xlsx"))
```





