# Appendix
## Norway

```{r, echo=FALSE, results='asis'}
counties <- c("Oestfold",
              "Akershus",
              "Oslo",
              "Hedmark",
              "Oppland",
              "Buskerud",
              "Vestfold",
              "Telemark",
              "Aust-Agder",
              "Vest-Agder",
              "Rogaland",
              "Hordaland",
              "Sogn-og-fjordane",
              "Moere-og-Romsdal",
              "Soer-Troendelag",
              "Nord-Troendelag",
              "Nordland",
              "Troms",
              "Finnmark-Finnmarku")
for(i in counties){
  cat("### ",i,"\n\n")
  
  cat(readRDS(paste0("results_final/corr_",i,".RDS")))
}
```

## South Sudan

```{r, echo=FALSE, results='asis'}
counties <- c("Gogrial",
              "Doro",
              "Bunj",
              "Pibor",
              "GMK",
              "LKG")
for(i in counties){
  cat("### ",i,"\n\n")
  
  cat(readRDS(paste0("results_final/corr_",i,".RDS")))
}
```
